version: '2'

services:
  bioportainer:
    image: bioportainer/bioportainer
    container_name: "bioportainer-base"
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/bioportainer/bioportainer_data:/data
      
  bioportainer-pipeline-runner:
    image: bioportainer/pipeline-runner
    container_name: "bioportainer-pipeline-runner"
    privileged: true
    ports:
      - "5000:5000"
      - "5001:5001"
      - "5002:5002"
    networks:
      - local
    volumes:
      - ${PWD}/bioportainer/bioportainer_workdir:/root/workdir/data
      - ${PWD}/bioportainer/bioportainer_notebooks:/root/workdir/notebooks
      - ${PWD}/bioportainer/bioportainer_examples:/root/workdir/examples
      - ${PWD}/bioportainer/bioportainer_nextflow:/root/workdir/.nextflow/assets/nextflow-io/
      
  bioportainer-watchtower:
    image: v2tec/watchtower
    container_name: "bioportainer-watchtower"
    command: --cleanup portainer-base bioportainer-watchtower bioportainer-pipeline-runner
    networks:
      - local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  local:
    driver: bridge
