version: '3.2'

services:
  bioportainer-panel:
    image: bioportainer/bioportainer-panel
    stdin_open: true
    ports:
      - "9000:9000"
      - "6000:6000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - bioportainer_data:/data
    networks:
      - bioportainer-local
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  bioportainer-local:
    driver: overlay
    attachable: true

volumes:
    bioportainer_data:
