version: '3.2'

services:
  bioportainer-panel:
    image: bioportainer/bioportainer-panel
    stdin_open: true
    restart: always
    ports:
      - "9000:9000"
      - "6000:6000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - bioportainer_data:/data
    networks:
      - bioportainer-local
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  bioportainer-pipeline-runner:
    image: portainer/portainer
    stdin_open: true
    restart: always
    ports:
      - "5000:5000"
      - "8888:8888"
      - "7000:7000"
    volumes:
      - bioportainer_workdir:/root/workdir/data
      - bioportainer_nextflow:/root/workdir/.nextflow/assets/nextflow-io/
    networks:
      - bioportainer-local
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
        
  bioportainer-watchtower:
    image: v2tec/watchtower
    stdin_open: true
    restart: always
    command: --cleanup portainer-base bioportainer-watchtower bioportainer-pipeline-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - bioportainer-local
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
        
networks:
  bioportainer-local:
    driver: overlay
    attachable: true

volumes:
    bioportainer_data:
    bioportainer_workdir:
    bioportainer_nextflow:
