version: '3.2'

services:
  agent:
    image: portainer/agent
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - bioportainer-local
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  bioportainer-panel:
    image: bioportainer/bioportainer-panel
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    stdin_open: true
    ports:
      - "9000:9000"
      - "6000:6000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - bioportainer_data:/data
    networks:
      - bioportainer-local
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints: [node.role == manager]

networks:
  bioportainer-local:
    driver: overlay
    attachable: true

volumes:
    bioportainer_data:
